### ISSUE TITLE
环境配置好了 打卡成功但是psuhplus推送失败

### ISSUE THREAD

**Issue by zlx2** [jimlee2002/Actions-WoZaiXiaoYuanPuncher#52]
![image](https://user-images.githubusercontent.com/61264911/165205192-649effcb-ab52-48bc-96eb-7d9e1bf48467.png)

**Comment by zlx2** [comment]
然后我重新运行了一遍

**Comment by zlx2** [comment]
然后我重新运行了一遍
变成了下面这个样子


找不到cache文件，正在使用账号信息登录...
Traceback (most recent call last):
  File "/home/runner/work/Actions-WoZaiXiaoYuanPuncher/Actions-WoZaiXiaoYuanPuncher/wzxy-healthcheck.py", line 269, in <module>
{'code': 101, 'message': '用户名或密码错误,还可再试4次'}
    wzxy.sendNotification()
  File "/home/runner/work/Actions-WoZaiXiaoYuanPuncher/Actions-WoZaiXiaoYuanPuncher/wzxy-healthcheck.py", line 197, in sendNotification
    print("pushplus: " + r['code'] + ": " + r['msg'])
TypeError: can only concatenate str (not "int") to str
登录失败，请检查账号信息
登陆失败，请检查账号信息
Error: Process completed with exit code 1.
